on:
  push:
  workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4.1.2
            
          - name: Run PowerShell Script
            run: pwsh -file generate_names.ps1
    job2:
        runs-on: ubuntu latest
        steps:
          - name: Sleep 3 Seconds
            run: sleep 3
    job3:
        needs:
          - job1
          - job2
        runs-on: ubuntu latest
        steps:
          - name: Sleep 5 Seconds
            run: sleep 5
