on:
  push:
  workflow_dispatch:

jobs:
    job1:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Repository
            uses: actions/checkout@v4.1.2
            
          - name: Run PowerShell Script
            run: pwsh -file generate_names.ps1
        
